### PR TITLE
Rspec model user

### PR DESCRIPTION
**Pull request by tranxuanhaibk**
## Related Tickets
- [#44139](https://edu-redmine.sun-asterisk.vn/issues/44139)

## WHAT (optional)
* Mục đích: Viết unit test cho model user

## Evidence (Screenshot or Video)
----------------- PASS RUBOCOP---------------------
Screenshot from 2021-12-13 11-18-29

### CODE REVIEW

**Comment by tranxuanhaibk** [comment]
ready

**Review by ghost — COMMENTED** [review]
Tách ra làm 2 pull request đi em

**Comment by tranxuanhaibk** [comment]
ready

**Review by ghost — COMMENTED** [review]
merged

**Pull request merged**
