### PR TITLE
Sign in

### PR DESCRIPTION
**Pull request by tranxuanhaibk**
## Related Tickets
- [#43395](https://edu-redmine.sun-asterisk.vn/issues/43395)

## WHAT (optional)
- Thiết lập layout, css login
- Thiết lập basic login, remember me

## HOW
- Tạo controller Sessions, helper, model user

## Evidence (Screenshot or Video)
Screenshot from 2021-11-20 21-53-10
Screenshot from 2021-11-20 21-53-35

### CODE REVIEW

**Comment by nguyenvanson332000** [comment]
ready

**Comment by tranxuanhaibk** [comment]
ready

**Comment by tranxuanhaibk** [comment]
ready

**Comment by tranxuanhaibk** [comment]
ready

**Pull request merged**
