### PR TITLE
Account activation

### PR DESCRIPTION
**Pull request by nguyenvanson332000**
## Related Tickets
- [#43481](https://edu-redmine.sun-asterisk.vn/issues/43481)

## WHAT (optional)
- Activate account by email

## HOW
- Generate controller Accounts_activations
- Generate Mailer/user_mailer

## Evidence (Screenshot or Video)
ảnh
ảnh

### CODE REVIEW

**Comment by tranxuanhaibk** [comment]
ready

**Comment by nguyenvanson332000** [comment]
Ready

**Comment by quoctd-0607** [comment]
conflict

**Comment by quoctd-0607** [comment]
commented
conflict code e

**Comment by nguyenvanson332000** [comment]
dạ vâng ạ em fix liền ạ

**Pull request closed without merging**
