### PR TITLE
Rspec view users new

### PR DESCRIPTION
**Pull request by tranxuanhaibk**
## Related Tickets
- [#44137](https://edu-redmine.sun-asterisk.vn/issues/44137)

## WHAT (optional)
- Viết unit test cho view (edit user).

## Evidence (Screenshot or Video)
------------------- PASS RUBOCOP --------------------
Screenshot from 2021-12-13 10-55-08

### CODE REVIEW

**Comment by tranxuanhaibk** [comment]
ready

**Review by ghost — COMMENTED** [review]
Em đẩy 2 pull liên tiếp à. rồi merged pull nào trước pull nào sau ?????

**Comment by tranxuanhaibk** [comment]
ready

**Comment by tranxuanhaibk** [comment]
ready

**Review by ghost — COMMENTED** [review]
merged

**Pull request merged**
