### PR TITLE
Sign up

### PR DESCRIPTION
**Pull request by nguyenvanson332000**
## Related Tickets
- [#43398](https://edu-redmine.sun-asterisk.vn/issues/43398)

## WHAT (optional)
- Build SignUp for users

## HOW
- Sign up form (email, password), send msg
- Setting config routes

## Evidence (Screenshot or Video)
ảnh
ảnh

### CODE REVIEW

**Comment by tranxuanhaibk** [comment]
Ready

**Comment by nguyenvanson332000** [comment]
ready

**Comment by nguyenvanson332000** [comment]
ready

**Comment by tranxuanhaibk** [comment]
ready

**Pull request merged**
